[DO NOT MERGE] Test CI failure

diff --git a/.github/workflows/pinot_tests.yml b/.github/workflows/pinot_tests.yml
--- a/.github/workflows/pinot_tests.yml
+++ b/.github/workflows/pinot_tests.yml
@@ -38,24 +38,25 @@ on:
       - "**.md"
 
 jobs:
-  linter-test:
-    runs-on: ubuntu-latest
-    name: Pinot Linter Test Set
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 11
-      - name: Linter Test
-        env:
-          MAVEN_OPTS: -Xmx2G -DskipShade -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
-        run: .github/workflows/scripts/.pinot_linter.sh
+#  linter-test:
+#    runs-on: ubuntu-latest
+#    name: Pinot Linter Test Set
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 11
+#      - name: Linter Test
+#        env:
+#          MAVEN_OPTS: -Xmx2G -DskipShade -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
+#        run: .github/workflows/scripts/.pinot_linter.sh
   unit-test:
     runs-on: ubuntu-latest
     strategy:
       matrix:
-        testset: [ 1, 2 ]
+#        testset: [ 1, 2 ]
+        testset: [ 1 ]
     name: Pinot Unit Test Set ${{ matrix.testset }}
     steps:
       - uses: actions/checkout@v2
@@ -80,105 +81,105 @@ jobs:
         run: |
           bash <(curl -s https://codecov.io/bash) -cF unittests${{ matrix.testset }}
 
-  integration-test:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        testset: [ 1, 2 ]
-    name: Pinot Integration Test Set ${{ matrix.testset }}
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 11
-      # Step that does that actual cache save and restore
-      - uses: actions/cache@v1
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-      - name: Integration Test
-        env:
-          RUN_INTEGRATION_TESTS: true
-          RUN_TEST_SET: ${{ matrix.testset }}
-          MAVEN_OPTS: -Xmx2G -DskipShade -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
-        run: .github/workflows/scripts/.pinot_test.sh
-      - name: Upload coverage to Codecov
-        run: |
-          bash <(curl -s https://codecov.io/bash) -cF integration${{ matrix.testset }}
-
-  compatibility-verifier:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        test_suite: [ "compatibility-verifier/sample-test-suite" ]
-        old_commit: [ "release-0.7.1", "master" ]
-    name: Pinot Compatibility Regression Testing against ${{ matrix.old_commit }} on ${{ matrix.test_suite }}
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
-        with:
-          java-version: 1.8
-      # Step that does that actual cache save and restore
-      - uses: actions/cache@v1
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-      - name: Pinot Compatibility Regression Testing
-        env:
-          OLD_COMMIT: ${{ matrix.old_commit }}
-          WORKING_DIR: /tmp/compatibility-verifier
-          TEST_SUITE: ${{ matrix.test_suite }}
-          MAVEN_OPTS: -Xmx2G -DskipShade -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
-        run: .github/workflows/scripts/.pinot_compatibility_verifier.sh
-
-  quickstarts:
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        java: [ 1.8, 10, 11, 12, 13, 14, 15 ]
-    name: Pinot Quickstart on JDK ${{ matrix.java }}
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK ${{ matrix.java }}
-        uses: actions/setup-java@v1
-        with:
-          java-version: ${{ matrix.java }}
-      # Step that does that actual cache save and restore
-      - uses: actions/cache@v1
-        with:
-          path: ~/.m2/repository
-          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
-          restore-keys: |
-            ${{ runner.os }}-maven-
-      - name: Quickstart on JDK ${{ matrix.java }}
-        run: .github/workflows/scripts/.pinot_quickstart.sh
-
-  presto-driver-build:
-    runs-on: ubuntu-latest
-    name: Build Presto Pinot Driver
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up JDK 11
-        uses: actions/setup-java@v1
-        with:
-          java-version: 11
-      - name: Build presto pinot driver with JDK 11
-        env:
-          MAVEN_OPTS: -Xmx2G -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
-        run: |
-          mvn clean install -DskipTests -Ppresto-driver -am -B -pl ':presto-pinot-driver' -T 16 || exit 1
-      - name: Set up JDK 8
-        uses: actions/setup-java@v1
-        with:
-          java-version: 8
-      - name: Build presto pinot driver with JDK 8
-        env:
-          MAVEN_OPTS: -Xmx2G -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
-        run: |
-          mvn clean install -DskipTests -Ppresto-driver -am -B -pl ':presto-pinot-driver' -Djdk.version=8 -T 16 || exit 1
+#  integration-test:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        testset: [ 1, 2 ]
+#    name: Pinot Integration Test Set ${{ matrix.testset }}
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 11
+#      # Step that does that actual cache save and restore
+#      - uses: actions/cache@v1
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#      - name: Integration Test
+#        env:
+#          RUN_INTEGRATION_TESTS: true
+#          RUN_TEST_SET: ${{ matrix.testset }}
+#          MAVEN_OPTS: -Xmx2G -DskipShade -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
+#        run: .github/workflows/scripts/.pinot_test.sh
+#      - name: Upload coverage to Codecov
+#        run: |
+#          bash <(curl -s https://codecov.io/bash) -cF integration${{ matrix.testset }}
+#
+#  compatibility-verifier:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        test_suite: [ "compatibility-verifier/sample-test-suite" ]
+#        old_commit: [ "release-0.7.1", "master" ]
+#    name: Pinot Compatibility Regression Testing against ${{ matrix.old_commit }} on ${{ matrix.test_suite }}
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up JDK 1.8
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 1.8
+#      # Step that does that actual cache save and restore
+#      - uses: actions/cache@v1
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#      - name: Pinot Compatibility Regression Testing
+#        env:
+#          OLD_COMMIT: ${{ matrix.old_commit }}
+#          WORKING_DIR: /tmp/compatibility-verifier
+#          TEST_SUITE: ${{ matrix.test_suite }}
+#          MAVEN_OPTS: -Xmx2G -DskipShade -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
+#        run: .github/workflows/scripts/.pinot_compatibility_verifier.sh
+#
+#  quickstarts:
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        java: [ 1.8, 10, 11, 12, 13, 14, 15 ]
+#    name: Pinot Quickstart on JDK ${{ matrix.java }}
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up JDK ${{ matrix.java }}
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: ${{ matrix.java }}
+#      # Step that does that actual cache save and restore
+#      - uses: actions/cache@v1
+#        with:
+#          path: ~/.m2/repository
+#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+#          restore-keys: |
+#            ${{ runner.os }}-maven-
+#      - name: Quickstart on JDK ${{ matrix.java }}
+#        run: .github/workflows/scripts/.pinot_quickstart.sh
+#
+#  presto-driver-build:
+#    runs-on: ubuntu-latest
+#    name: Build Presto Pinot Driver
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up JDK 11
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 11
+#      - name: Build presto pinot driver with JDK 11
+#        env:
+#          MAVEN_OPTS: -Xmx2G -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
+#        run: |
+#          mvn clean install -DskipTests -Ppresto-driver -am -B -pl ':presto-pinot-driver' -T 16 || exit 1
+#      - name: Set up JDK 8
+#        uses: actions/setup-java@v1
+#        with:
+#          java-version: 8
+#      - name: Build presto pinot driver with JDK 8
+#        env:
+#          MAVEN_OPTS: -Xmx2G -DfailIfNoTests=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=25 -Dmaven.wagon.http.retryHandler.count=3 -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false
+#        run: |
+#          mvn clean install -DskipTests -Ppresto-driver -am -B -pl ':presto-pinot-driver' -Djdk.version=8 -T 16 || exit 1
